export const ADD_MOVIES = "ADD_MOVIES";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const SET_LOADING = "SET_LOADING";
export const ADD_SHORTLISTED_MOVIES = "ADD_SHORTLISTED_MOVIES";
export const CLEAR_SHORTLISTED_MOVIES = "CLEAR_SHORTLISTED_MOVIES";